### ISSUE TITLE
[Bug][1.18.2] Can't fish if the queue is empty?

### ISSUE THREAD

**Issue by drakray** [hjake123/lost-and-found#4]
MC 1.18.2
Forge 40.1.93
LostnFished 1.0
+Other mods

If the queue is empty(made sure by either fishing back everything, or deleting in the capabilities file), right-clicking to reel does nothing, and this is logged in debug.log

<details><summary>log snippet</summary>

```
[31Dec.2022 00:09:30.697] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.teammetallurgy.aquaculture.loot.FishWeightHandler onItemFished(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		2: ASM: com.hyperlynx.lost_found.LostFoundMod@d8c87b9 onItemFished(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		3: ASM: class cy.jdkdigital.productivebees.event.EventHandler onItemFished(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		4: LOW
		5: ASM: class cofh.ensorcellation.event.CommonEvents handleItemFishedEvent(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		6: LOWEST
		7: ASM: class cofh.core.event.CoreCommonEvents handleItemFishedEvent(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
	at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:523)
	at TRANSFORMER/lost_found@1.0/com.hyperlynx.lost_found.capabilities.WorldInventoryImplementation.popItem(WorldInventoryImplementation.java:20)
	at TRANSFORMER/lost_found@1.0/com.hyperlynx.lost_found.LostFoundMod.onItemFished(LostFoundMod.java:72)
	at net.minecraftforge.eventbus.ASMEventHandler_1592_LostFoundMod_onItemFished_ItemFishedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.projectile.FishingHook.m_37156_(FishingHook.java:417)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.FishingRodItem.m_7203_(FishingRodItem.java:24)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:291)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1015)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[31Dec.2022 00:09:30.697] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@13890726, suppressing error
java.util.NoSuchElementException: null
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:362) ~[?:?]
	at java.util.ArrayDeque.remove(ArrayDeque.java:523) ~[?:?]
	at com.hyperlynx.lost_found.capabilities.WorldInventoryImplementation.popItem(WorldInventoryImplementation.java:20) ~[lost-and-fished-1.18.2-1.0.jar%23259!/:1.0]
	at com.hyperlynx.lost_found.LostFoundMod.onItemFished(LostFoundMod.java:72) ~[lost-and-fished-1.18.2-1.0.jar%23259!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_1592_LostFoundMod_onItemFished_ItemFishedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.world.entity.projectile.FishingHook.m_37156_(FishingHook.java:417) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.world.item.FishingRodItem.m_7203_(FishingRodItem.java:24) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:291) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[31Dec.2022 00:09:31.860] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.teammetallurgy.aquaculture.loot.FishWeightHandler onItemFished(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		2: ASM: com.hyperlynx.lost_found.LostFoundMod@d8c87b9 onItemFished(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		3: ASM: class cy.jdkdigital.productivebees.event.EventHandler onItemFished(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		4: LOW
		5: ASM: class cofh.ensorcellation.event.CommonEvents handleItemFishedEvent(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
		6: LOWEST
		7: ASM: class cofh.core.event.CoreCommonEvents handleItemFishedEvent(Lnet/minecraftforge/event/entity/player/ItemFishedEvent;)V
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:362)
	at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:523)
	at TRANSFORMER/lost_found@1.0/com.hyperlynx.lost_found.capabilities.WorldInventoryImplementation.popItem(WorldInventoryImplementation.java:20)
	at TRANSFORMER/lost_found@1.0/com.hyperlynx.lost_found.LostFoundMod.onItemFished(LostFoundMod.java:72)
	at net.minecraftforge.eventbus.ASMEventHandler_1592_LostFoundMod_onItemFished_ItemFishedEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.entity.projectile.FishingHook.m_37156_(FishingHook.java:417)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.FishingRodItem.m_7203_(FishingRodItem.java:24)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:291)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1015)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[31Dec.2022 00:09:31.860] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@555bfbcf, suppressing error
java.util.NoSuchElementException: null
	at java.util.ArrayDeque.removeFirst(ArrayDeque.java:362) ~[?:?]
	at java.util.ArrayDeque.remove(ArrayDeque.java:523) ~[?:?]
	at com.hyperlynx.lost_found.capabilities.WorldInventoryImplementation.popItem(WorldInventoryImplementation.java:20) ~[lost-and-fished-1.18.2-1.0.jar%23259!/:1.0]
	at com.hyperlynx.lost_found.LostFoundMod.onItemFished(LostFoundMod.java:72) ~[lost-and-fished-1.18.2-1.0.jar%23259!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_1592_LostFoundMod_onItemFished_ItemFishedEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraft.world.entity.projectile.FishingHook.m_37156_(FishingHook.java:417) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.world.item.FishingRodItem.m_7203_(FishingRodItem.java:24) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:252) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:291) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:25) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23330!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[31Dec.2022 00:09:34.026] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Saving and pausing game...
```
</details>

When the "fish" is gone, I can reel with nothing on the line
Removing LostNFished fixes the problem

---
Also suggestion, adding minecraft:player_head to the default no_save tag, as some mods add custom mods head via this, and mobs dying fill the queue with head(mainly bats as they have tendency to die by themselves in large caves)

**Comment by hjake123** [comment]
Ah thanks for catching that, I'll get right on it!

**Comment by hjake123** [comment]
That should do it
